# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/new_bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_bill(object):
    def setupUi(self, new_bill):
        new_bill.setObjectName("new_bill")
        new_bill.resize(1147, 849)
        new_bill.setStyleSheet("background-color:rgb(8, 32, 50)")
        self.centralwidget = QtWidgets.QWidget(new_bill)
        self.centralwidget.setStyleSheet("QLineEdit\n"
            "{\n"
            "border-radius: 5px;\n"
            "padding-left: 5px;\n"
            "background-color: rgb(77, 109, 130);\n"
            "color: rgb(255,255,255)\n"
            "}\n"
            "\n"
            "QPushButton\n"
            "{\n"
            "background-color: rgb(51, 71, 86);\n"
            "border-radius: 15px;\n"
            "color: rgb(255,255,255);\n"
            "}\n"
            "\n"
            "QPushButton::hover\n"
            "{\n"
            "background-color: rgb(77, 109, 130);\n"
            "border-radius: 15px;\n"
            "color: rgb(255,255,255);\n"
            "}\n"
            "\n"
            "QPushButton::pressed\n"
            "{\n"
            "background-color: rgb(60, 86, 102);\n"
            "border-radius: 15px;\n"
            "color: rgb(255,255,255);\n"
            "}\n"
            "\n"
            "QPushButton#button_search\n"
            "{\n"
            "background-color: rgb(25, 188, 142);\n"
            "border-radius: 10px;\n"
            "color: rgb(0, 0, 0);\n"
            "}\n"
            "\n"
            "QPushButton#button_search::hover\n"
            "{\n"
            "background-color: rgb(30, 229, 173);\n"
            "border-radius: 10px;\n"
            "color: rgb(0, 0, 0);\n"
            "}\n"
            "\n"
            "QPushButton#button_search::pressed\n"
            "{\n"
            "background-color: rgb(25, 188, 142);\n"
            "border-radius: 10px;\n"
            "color: rgb(0, 0, 0);\n"
            "}\n"
            "\n"
            "QLabel\n"
            "{\n"
            "color: rgb(255,255,255);\n"
            "}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.LE_bill_no = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_bill_no.sizePolicy().hasHeightForWidth())
        self.LE_bill_no.setSizePolicy(sizePolicy)
        self.LE_bill_no.setObjectName("LE_bill_no")
        self.horizontalLayout_3.addWidget(self.LE_bill_no)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.LE_cust_id = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_cust_id.sizePolicy().hasHeightForWidth())
        self.LE_cust_id.setSizePolicy(sizePolicy)
        self.LE_cust_id.setObjectName("LE_cust_id")
        self.horizontalLayout_3.addWidget(self.LE_cust_id)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.LE_cust_name = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_cust_name.sizePolicy().hasHeightForWidth())
        self.LE_cust_name.setSizePolicy(sizePolicy)
        self.LE_cust_name.setObjectName("LE_cust_name")
        self.horizontalLayout_4.addWidget(self.LE_cust_name)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.LE_address = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_address.sizePolicy().hasHeightForWidth())
        self.LE_address.setSizePolicy(sizePolicy)
        self.LE_address.setObjectName("LE_address")
        self.horizontalLayout_5.addWidget(self.LE_address)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.LE_mob_no = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_mob_no.sizePolicy().hasHeightForWidth())
        self.LE_mob_no.setSizePolicy(sizePolicy)
        self.LE_mob_no.setObjectName("LE_mob_no")
        self.horizontalLayout_6.addWidget(self.LE_mob_no)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setStyleSheet("color: rgb(255,255,255)")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_7.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.LE_reg_1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_reg_1.sizePolicy().hasHeightForWidth())
        self.LE_reg_1.setSizePolicy(sizePolicy)
        self.LE_reg_1.setObjectName("LE_reg_1")
        self.horizontalLayout_8.addWidget(self.LE_reg_1)
        self.LE_reg_2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_reg_2.sizePolicy().hasHeightForWidth())
        self.LE_reg_2.setSizePolicy(sizePolicy)
        self.LE_reg_2.setObjectName("LE_reg_2")
        self.horizontalLayout_8.addWidget(self.LE_reg_2)
        self.LE_reg_3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_reg_3.sizePolicy().hasHeightForWidth())
        self.LE_reg_3.setSizePolicy(sizePolicy)
        self.LE_reg_3.setObjectName("LE_reg_3")
        self.horizontalLayout_8.addWidget(self.LE_reg_3)
        self.LE_reg_4 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_reg_4.sizePolicy().hasHeightForWidth())
        self.LE_reg_4.setSizePolicy(sizePolicy)
        self.LE_reg_4.setObjectName("LE_reg_4")
        self.horizontalLayout_8.addWidget(self.LE_reg_4)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_8.setStretch(2, 3)
        self.horizontalLayout_8.setStretch(3, 3)
        self.horizontalLayout_8.setStretch(4, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.LE_make_model = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_make_model.sizePolicy().hasHeightForWidth())
        self.LE_make_model.setSizePolicy(sizePolicy)
        self.LE_make_model.setObjectName("LE_make_model")
        self.horizontalLayout_9.addWidget(self.LE_make_model)
        self.horizontalLayout_9.setStretch(0, 2)
        self.horizontalLayout_9.setStretch(1, 7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, 10, 5, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.LE_km_reading = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_km_reading.sizePolicy().hasHeightForWidth())
        self.LE_km_reading.setSizePolicy(sizePolicy)
        self.LE_km_reading.setObjectName("LE_km_reading")
        self.horizontalLayout_10.addWidget(self.LE_km_reading)
        self.CHK_next_km_reading = QtWidgets.QCheckBox(self.centralwidget)
        self.CHK_next_km_reading.setStyleSheet("color: rgb(255,255,255)")
        self.CHK_next_km_reading.setObjectName("CHK_next_km_reading")
        self.horizontalLayout_10.addWidget(self.CHK_next_km_reading)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 3)
        self.horizontalLayout_10.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.TBL_parts = QtWidgets.QTableWidget(self.centralwidget)
        self.TBL_parts.setRowCount(10)
        self.TBL_parts.setObjectName("TBL_parts")
        self.TBL_parts.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_parts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_parts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_parts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_parts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_parts.setHorizontalHeaderItem(4, item)
        self.verticalLayout_5.addWidget(self.TBL_parts)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.TBL_labour = QtWidgets.QTableWidget(self.centralwidget)
        self.TBL_labour.setStyleSheet("")
        self.TBL_labour.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TBL_labour.setRowCount(10)
        self.TBL_labour.setObjectName("TBL_labour")
        self.TBL_labour.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_labour.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_labour.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TBL_labour.setHorizontalHeaderItem(2, item)
        self.TBL_labour.horizontalHeader().setCascadingSectionResizes(False)
        self.TBL_labour.horizontalHeader().setSortIndicatorShown(False)
        self.TBL_labour.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.TBL_labour)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        new_bill.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(new_bill)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1147, 27))
        self.menubar.setObjectName("menubar")
        new_bill.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(new_bill)
        self.statusbar.setObjectName("statusbar")
        new_bill.setStatusBar(self.statusbar)


        header_TBL_parts = self.TBL_parts.horizontalHeader()
        header_TBL_parts.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header_TBL_parts.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header_TBL_parts.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)

        header_TBL_labour = self.TBL_labour.horizontalHeader()
        header_TBL_labour.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header_TBL_labour.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header_TBL_labour.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)

        self.retranslateUi(new_bill)
        QtCore.QMetaObject.connectSlotsByName(new_bill)

    def retranslateUi(self, new_bill):
        _translate = QtCore.QCoreApplication.translate
        new_bill.setWindowTitle(_translate("new_bill", "MainWindow"))
        self.label.setText(_translate("new_bill", "Bill Number"))
        self.label_3.setText(_translate("new_bill", "Customer ID"))
        self.label_4.setText(_translate("new_bill", "Customer Name"))
        self.label_5.setText(_translate("new_bill", "Address"))
        self.label_6.setText(_translate("new_bill", "Mobile Number"))
        self.label_2.setText(_translate("new_bill", "Date"))
        self.label_7.setText(_translate("new_bill", "Registration Number"))
        self.label_8.setText(_translate("new_bill", "Make and Model"))
        self.label_9.setText(_translate("new_bill", "Km reading"))
        self.CHK_next_km_reading.setText(_translate("new_bill", "Include Next service Km reading"))
        self.label_10.setText(_translate("new_bill", "PARTS"))
        item = self.TBL_parts.horizontalHeaderItem(0)
        item.setText(_translate("new_bill", "Particulars"))
        item = self.TBL_parts.horizontalHeaderItem(1)
        item.setText(_translate("new_bill", "HSN Code"))
        item = self.TBL_parts.horizontalHeaderItem(2)
        item.setText(_translate("new_bill", "Rate"))
        item = self.TBL_parts.horizontalHeaderItem(3)
        item.setText(_translate("new_bill", "Quantity"))
        item = self.TBL_parts.horizontalHeaderItem(4)
        item.setText(_translate("new_bill", "Amount"))
        self.label_11.setText(_translate("new_bill", "LABOUR"))
        item = self.TBL_labour.horizontalHeaderItem(0)
        item.setText(_translate("new_bill", "Particulars"))
        item = self.TBL_labour.horizontalHeaderItem(1)
        item.setText(_translate("new_bill", "HSN code"))
        item = self.TBL_labour.horizontalHeaderItem(2)
        item.setText(_translate("new_bill", "Amount"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_bill = QtWidgets.QMainWindow()
    ui = Ui_new_bill()
    ui.setupUi(new_bill)
    new_bill.show()
    sys.exit(app.exec_())
